name: Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      source:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy:
    name: Merge to canary branch
    uses: ./.github/workflows/fast-forward.yml
    with:
      env: ${{ inputs.env }}-canary
      source: ${{ inputs.source }}
    secrets:
      token: ${{ secrets.token }}
  
  tests:
    needs: deploy
    name: Run smoke tests
    uses: ./.github/workflows/tests.yml
    with:
      env: ${{ inputs.env }}

  merge:
    needs: tests
    name: Merge to release branch
    uses: ./.github/workflows/fast-forward.yml
    with:
      env: ${{ inputs.env }}
      source: ${{ inputs.source }}
    secrets:
      token: ${{ secrets.token }}
