name: ephemeral

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  create:
    name: Create ephemeral cluster
    runs-on: ubuntu-latest
    steps:
      - name: terraform apply
        run: |
          echo "terraform creates cluster"

  tests:
    uses: ./.github/workflows/tests.yml
