name: "release-please"

on:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          target-branch: main
          token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        if: steps.release.outputs.releases_created
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  testnet:
    if: needs.release-please.outputs.spectrum-release-created
    needs: release-please
    uses: ./.github/workflows/deploy.yml
    with:
      env: testnet
    secrets:
      token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}

  mainnet:
    if: needs.release-please.outputs.spectrum-release-created
    needs:
      - release-please
      - testnet
    uses: ./.github/workflows/deploy.yml
    with:
      env: mainnet
    secrets:
      token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
