name: tests

on:
  workflow_call:
    inputs:
      env:
        type: string

jobs:
  tests:
    name: Run k8s e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: some tests
        run: |
          sleep 20
